[package]
name = "optimized-hd2sd"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
walkdir = "2.3.2"
image = "0.25.2"
rfd = "0.14.1"
oxipng = "9.1.2"
rayon = "1.10.0"