[package]
name = "optimized-hd2sd"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
walkdir = "2.3.2"
image = "0.24.5"
rfd = "0.10.0"
oxipng = "6.0.0"